Repository CookingAtKIT/cak-core, pull requests merged in 2020-10, with the labels that each got.

#6 Update config.ts
  src/structs/config.ts
Labels: bug, security

#8 Add GitHub actions to automate development process
  .github/workflows/node.js.yml
  .github/workflows/stale.yml
Labels: enhancement, security

#7 Updated README
  README.md
Labels: documentation

#9 Use yarn in dockerfile
  Dockerfile
Labels: enhancement

#21 Add mongoose schemas and enfore code style
  .prettierrc
  package.json
  src/main.ts
  src/models/allergen.schema.ts
  src/models/allergen.types.ts
  src/models/comment.schema.ts
  src/models/comment.types.ts
  src/models/image.schema.ts
  src/models/image.types.ts
  src/models/ingredient.schema.ts
  src/models/ingredient.types.ts
  src/models/recipe.schema.ts
  src/models/recipe.ts
  src/models/recipe.types.ts
  src/models/unit.schema.ts
  src/models/unit.types.ts
  src/models/user.schema.ts
  src/models/user.types.ts
  src/routes/index.ts
  src/routes/recipe.ts
  src/structs/config.ts
  yarn.lock
Labels: enhancement

#23 Remove _id from schema and fix model typings
  src/models/allergen.schema.ts
  src/models/comment.schema.ts
  src/models/image.schema.ts
  src/models/ingredient.schema.ts
  src/models/recipe.schema.ts
  src/models/unit.schema.ts
  src/models/user.schema.ts
Labels: bug

#24 Implemented health checking for mongodb and minio servers
  package.json
  src/routes/index.ts
  src/structs/config.ts
  src/structs/database.ts
  yarn.lock
Labels: enhancement

#30 Implement morgan middleware
  .gitignore
  package.json
  src/main.ts
  src/structs/logger.ts
  yarn.lock
Labels: enhancement

#35 Minio routes
  src/main.ts
  src/routes/upload.ts
Labels: enhancement

#33 Added 'uploader: ObjectId' field to Image collection
  src/models/image.schema.ts
  src/models/image.types.ts
Labels: discussion, enhancement

#36 Use refs and validators in schemas
  src/models/allergen.schema.ts
  src/models/allergen.types.ts
  src/models/comment.schema.ts
  src/models/comment.types.ts
  src/models/image.schema.ts
  src/models/image.types.ts
  src/models/ingredient.schema.ts
  src/models/ingredient.types.ts
  src/models/recipe.schema.ts
  src/models/recipe.types.ts
  src/models/unit.schema.ts
  src/models/unit.types.ts
  src/models/user.schema.ts
  src/models/user.types.ts
Labels: enhancement

#32 Implemented Authentication System
  package.json
  src/main.ts
  src/models/user.schema.ts
  src/models/user.types.ts
  src/models/usercodes.schema.ts
  src/models/usercodes.types.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/structs/config.ts
  src/structs/database.ts
  src/structs/email.ts
  yarn.lock
Labels: enhancement
